[package]
name = "backend_core"
version = "0.1.0"
edition = "2021"

[dependencies]
components = { path = "../components" }
context = { path = "../context" }
uuid = "*"
sqlx = { version = "*", features = ["runtime-tokio-rustls", "macros", "uuid"] }
