services:
  backend:
    privileged: true # 启用特权模式
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend_app
    networks:
      - dev-network
    ports:
      - "8000:8000"
    command: [ "tail", "-f", "/dev/null" ] # 保持容器运行

  frontend:
    privileged: true # 启用特权模式
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend_app
      - /frontend_app/node_modules # 防止 node_modules 被覆盖
    networks:
      - dev-network
    ports:
      - "5173:5173" # 前端 Vite 开发服务器默认端口
      - "5174:5174" # 避免端口冲突
    command: [ "tail", "-f", "/dev/null" ] # 保持容器运行
    environment:
      - NODE_ENV=development # 设置环境变量

networks:
  dev-network:
    driver: bridge
