[package]
name = "evo_sco_sim"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
axum = "0.7.5"
fs_extra = "1.3.0"
num = { version = "0.4.3", features = ["serde"] }
once_cell = "1.19.0"
# phf = { version = "0.11.2", features = ["macros"] }
rayon = "1.10.0"
sqlx = "0.8.2"
tokio = "1.40.0"
tracing = "0.1.40"
validator = { version = "0.18.1", features = ["derive"] }
# tracing-subscriber = "0.3.18"

[build-dependencies]
phf = { version = "0.11.2", features = ["macros"] }
convert_case = "0.6.0"
indoc = "2.0.5"
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
