[workspace]
members = [
    "app_context",
    "components",
    "database",
    "macros",
    "models",
    "repositories",
    "types",
]

[package]
name = "ess"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "*", features = ["full"] }
database = { path = "database" }


[[bin]]
name = "ess"
path = "src/main.rs"
