[workspace]
members = ["components", "utils"]

[package]
name = "ess"
version = "0.1.0"
edition = "2021"


[dependencies]
# tokio = { version = "*", features = ["full"] }


[[bin]]
name = "ess"
path = "src/main.rs"
