[workspace]
members = ["components", "context", "backend_core", "log", "utils"]

[package]
name = "ess"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "*", features = ["full"] }
axum = { version = "*", features = [] }
log = { path = "./log" }
context = { path = "./context" }
tracing = "*"

[[bin]]
name = "ess"
path = "src/main.rs"
