[package]
name = "components"
version = "0.1.0"
edition = "2021"

[dependencies]
num = { version = "*", features = ["serde"] }
once_cell = "*"
strum_macros = "*"
tracing = "*"
validator = "*"
macros = { path = "../macros" }
types = { path = "../types" }
